-- The Turndown immutable, database-first publication authority.
-- Populated-safe and replay-safe: every legacy row is versioned; only published rows become active.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE OR REPLACE FUNCTION public.content_uuid_from_hex(p_hex text) RETURNS uuid
LANGUAGE sql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $$
  SELECT (substr(p_hex,1,8)||'-'||substr(p_hex,9,4)||'-5'||substr(p_hex,14,3)||'-'||
    CASE WHEN substr(p_hex,17,1) IN ('0','4','8','c') THEN '8'
         WHEN substr(p_hex,17,1) IN ('1','5','9','d') THEN '9'
         WHEN substr(p_hex,17,1) IN ('2','6','a','e') THEN 'a' ELSE 'b' END ||
    substr(p_hex,18,3)||'-'||substr(p_hex,21,12))::uuid
$$;

CREATE OR REPLACE FUNCTION public.content_json_text_array(p_value text) RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE parsed jsonb;
BEGIN
  IF p_value IS NULL OR p_value='' THEN RETURN '[]'::jsonb; END IF;
  IF left(ltrim(p_value),1)='[' THEN
    BEGIN
      parsed:=p_value::jsonb;
      IF jsonb_typeof(parsed)<>'array' THEN RAISE EXCEPTION 'legacy JSON value is not an array'; END IF;
      RETURN parsed;
    EXCEPTION WHEN invalid_text_representation THEN
      IF right(rtrim(p_value),1)<>']' THEN RAISE EXCEPTION 'unterminated legacy bracket array'; END IF;
      SELECT coalesce(jsonb_agg(to_jsonb(btrim(entry, ' "')) ORDER BY ordinal),'[]'::jsonb)
        INTO parsed
      FROM unnest(string_to_array(substr(btrim(p_value),2,length(btrim(p_value))-2),',')) WITH ORDINALITY AS values(entry,ordinal)
      WHERE btrim(entry, ' "')<>'';
      RETURN parsed;
    END;
  END IF;
  IF left(ltrim(p_value),1)='{' THEN RETURN to_jsonb(p_value::text[]); END IF;
  RAISE EXCEPTION 'legacy array value is neither a JSON array nor a PostgreSQL text array';
END $$;

CREATE TABLE IF NOT EXISTS public.content_items (
  id uuid PRIMARY KEY,
  content_type text NOT NULL CHECK (content_type IN ('hotel','brand','destination','article')),
  slug text NOT NULL CHECK (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  legacy_id text NOT NULL,
  active_version_id uuid,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE(content_type,slug),
  UNIQUE(content_type,legacy_id),
  UNIQUE(id,content_type)
);

CREATE TABLE IF NOT EXISTS public.content_versions (
  id uuid PRIMARY KEY,
  item_id uuid NOT NULL REFERENCES public.content_items(id) ON DELETE RESTRICT,
  content_type text NOT NULL CHECK (content_type IN ('hotel','brand','destination','article')),
  schema_version integer NOT NULL CHECK (schema_version=1),
  payload jsonb NOT NULL,
  payload_checksum text NOT NULL CHECK (payload_checksum ~ '^sha256:[0-9a-f]{64}$'),
  source_evidence jsonb NOT NULL,
  media_manifest jsonb NOT NULL,
  legacy_snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL,
  run_id text NOT NULL,
  validation_result jsonb NOT NULL,
  UNIQUE(id,item_id),
  UNIQUE(item_id,payload_checksum),
  FOREIGN KEY(item_id,content_type) REFERENCES public.content_items(id,content_type) DEFERRABLE INITIALLY IMMEDIATE
);

DO $$ BEGIN
  ALTER TABLE public.content_items ADD CONSTRAINT content_items_active_version_owner_fk
    FOREIGN KEY(active_version_id,id) REFERENCES public.content_versions(id,item_id) DEFERRABLE INITIALLY IMMEDIATE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS public.content_publication_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  event_order bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  item_id uuid NOT NULL REFERENCES public.content_items(id) ON DELETE RESTRICT,
  event_type text NOT NULL CHECK (event_type IN ('bootstrap','published','reactivated','rolled_back','verified','verification_failed')),
  previous_version_id uuid,
  next_version_id uuid,
  actor text NOT NULL,
  run_id text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  verification_evidence jsonb,
  activation_event_id uuid REFERENCES public.content_publication_events(id) DEFERRABLE INITIALLY IMMEDIATE,
  predecessor_state jsonb,
  FOREIGN KEY(previous_version_id,item_id) REFERENCES public.content_versions(id,item_id) DEFERRABLE INITIALLY IMMEDIATE,
  FOREIGN KEY(next_version_id,item_id) REFERENCES public.content_versions(id,item_id) DEFERRABLE INITIALLY IMMEDIATE
);
ALTER TABLE public.content_publication_events ADD COLUMN IF NOT EXISTS event_order bigint GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS content_publication_events_order_unique ON public.content_publication_events(event_order);
CREATE UNIQUE INDEX IF NOT EXISTS content_activation_terminal_outcome_unique
  ON public.content_publication_events(activation_event_id)
  WHERE activation_event_id IS NOT NULL AND event_type IN ('verified','verification_failed');
CREATE INDEX IF NOT EXISTS content_versions_item_created_idx ON public.content_versions(item_id,created_at DESC);
CREATE INDEX IF NOT EXISTS content_events_item_order_idx ON public.content_publication_events(item_id,event_order DESC);

CREATE TABLE IF NOT EXISTS public.content_validation_keys (
  singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
  secret bytea NOT NULL CHECK(octet_length(secret)=32)
);
REVOKE ALL ON public.content_validation_keys FROM PUBLIC;

CREATE OR REPLACE FUNCTION public.content_payload_from_legacy(p_type text,p_row jsonb) RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
  CASE p_type
    WHEN 'hotel' THEN RETURN jsonb_build_object(
      'name',p_row->'name','brand',p_row->'brand','brandSlug',p_row->'brand_slug','location',p_row->'location',
      'country',p_row->'country','countrySlug',p_row->'country_slug','region',p_row->'region','regionSlug',p_row->'region_slug',
      'latitude',p_row->'latitude','longitude',p_row->'longitude','priceRange',p_row->'price_range','priceFrom',p_row->'price_from',
      'priceTo',p_row->'price_to','currency',p_row->'currency','style',p_row->'style',
      'bestFor',public.content_json_text_array(p_row->>'best_for'),'heroImage',p_row->'hero_image',
      'images',public.content_json_text_array(p_row->>'images'),'website',p_row->'website','bookingUrl',p_row->'booking_url',
      'tagline',p_row->'tagline','reviewIntro',p_row->'review_intro','reviewArrival',p_row->'review_arrival',
      'reviewRoom',p_row->'review_room','reviewService',p_row->'review_service','reviewFood',p_row->'review_food',
      'reviewDetails',p_row->'review_details','reviewVerdict',p_row->'review_verdict','verdictBestFor',p_row->'verdict_best_for',
      'verdictSkipIf',p_row->'verdict_skip_if','verdictStandout',p_row->'verdict_standout','ratingOverall',p_row->'rating_overall',
      'ratingRoom',p_row->'rating_room','ratingService',p_row->'rating_service','ratingFood',p_row->'rating_food',
      'ratingValue',p_row->'rating_value','ratingLocation',p_row->'rating_location','featured',coalesce((p_row->>'featured')::integer,0)=1,
      'createdAt',to_jsonb((p_row->>'created_at')::timestamptz),'updatedAt',to_jsonb((p_row->>'updated_at')::timestamptz));
    WHEN 'brand' THEN RETURN jsonb_build_object(
      'name',p_row->'name','tagline',p_row->'tagline','heroImage',p_row->'hero_image','contentMd',p_row->'content_md',
      'hotelCount',coalesce(p_row->'hotel_count','0'::jsonb),'foundedYear',p_row->'founded_year','parentCompany',p_row->'parent_company',
      'bestProperty',p_row->'best_property','website',p_row->'website','createdAt',to_jsonb((p_row->>'created_at')::timestamptz),
      'updatedAt',to_jsonb((p_row->>'updated_at')::timestamptz));
    WHEN 'destination' THEN RETURN jsonb_build_object(
      'name',p_row->'name','country',p_row->'country','region',p_row->'region','heroImage',p_row->'hero_image',
      'introMd',p_row->'intro_md','bestTime',p_row->'best_time','contentMd',p_row->'content_md',
      'createdAt',to_jsonb((p_row->>'created_at')::timestamptz),'updatedAt',to_jsonb((p_row->>'updated_at')::timestamptz));
    WHEN 'article' THEN RETURN jsonb_build_object(
      'title',p_row->'title','subtitle',p_row->'subtitle','category',p_row->'category','heroImage',p_row->'hero_image',
      'contentMd',p_row->'content_md','hotelsMentioned',public.content_json_text_array(p_row->>'hotels_mentioned'),
      'featured',coalesce((p_row->>'featured')::integer,0)=1,'createdAt',to_jsonb((p_row->>'created_at')::timestamptz),
      'updatedAt',to_jsonb((p_row->>'updated_at')::timestamptz));
    ELSE RAISE EXCEPTION 'unsupported content type' USING ERRCODE='22023';
  END CASE;
END $$;

-- Snapshot every predecessor table before any pointer is installed.
WITH legacy AS (
  SELECT 'hotel'::text content_type,id::text legacy_id,slug,coalesce(created_at,now()) created_at,coalesce(updated_at,created_at,now()) updated_at,to_jsonb(h.*) snapshot,coalesce(published,0)=1 published FROM public.hotels h
  UNION ALL SELECT 'brand',id::text,slug,coalesce(created_at,now()),coalesce(updated_at,created_at,now()),to_jsonb(b.*),coalesce(published,0)=1 FROM public.brands b
  UNION ALL SELECT 'destination',id::text,slug,coalesce(created_at,now()),coalesce(updated_at,created_at,now()),to_jsonb(d.*),coalesce(published,0)=1 FROM public.destinations d
  UNION ALL SELECT 'article',id::text,slug,coalesce(created_at,now()),coalesce(updated_at,created_at,now()),to_jsonb(a.*),coalesce(published,0)=1 FROM public.articles a
), prepared AS (
  SELECT *,encode(digest(convert_to(content_type||':'||slug,'UTF8'),'sha256'),'hex') item_hex FROM legacy
)
INSERT INTO public.content_items(id,content_type,slug,legacy_id,created_at,updated_at)
SELECT public.content_uuid_from_hex(item_hex),content_type,slug,legacy_id,created_at,updated_at FROM prepared
ON CONFLICT(content_type,slug) DO NOTHING;

WITH legacy AS (
  SELECT 'hotel'::text content_type,id::text legacy_id,slug,coalesce(created_at,now()) created_at,to_jsonb(h.*) snapshot FROM public.hotels h
  UNION ALL SELECT 'brand',id::text,slug,coalesce(created_at,now()),to_jsonb(b.*) FROM public.brands b
  UNION ALL SELECT 'destination',id::text,slug,coalesce(created_at,now()),to_jsonb(d.*) FROM public.destinations d
  UNION ALL SELECT 'article',id::text,slug,coalesce(created_at,now()),to_jsonb(a.*) FROM public.articles a
), canonical AS (
  SELECT l.*,i.id item_id,public.content_payload_from_legacy(l.content_type,l.snapshot) payload,
    jsonb_build_object('schemaVersion',1,'contentType',l.content_type,'slug',l.slug,'payload',public.content_payload_from_legacy(l.content_type,l.snapshot)) canonical
  FROM legacy l JOIN public.content_items i ON i.content_type=l.content_type AND i.slug=l.slug
  WHERE NOT EXISTS(SELECT 1 FROM public.content_versions v WHERE v.item_id=i.id)
), hashed AS (
  SELECT *,encode(digest(convert_to(canonical::text,'UTF8'),'sha256'),'hex') checksum_hex FROM canonical
)
INSERT INTO public.content_versions(id,item_id,content_type,schema_version,payload,payload_checksum,source_evidence,media_manifest,legacy_snapshot,created_at,created_by,run_id,validation_result)
SELECT public.content_uuid_from_hex(checksum_hex),item_id,content_type,1,payload,'sha256:'||checksum_hex,
  jsonb_build_object(
    'bootstrap',true,
    'source','exact-legacy-row',
    'normalizedLegacyArrayEncoding',CASE WHEN content_type='hotel' THEN jsonb_build_object(
      'bestForPostgresLiteral',coalesce(ltrim(snapshot->>'best_for') LIKE '{%',false),
      'imagesPostgresLiteral',coalesce(ltrim(snapshot->>'images') LIKE '{%',false),
      'bestForUnquotedBracketList',coalesce(ltrim(snapshot->>'best_for') LIKE '[%' AND ltrim(snapshot->>'best_for') NOT LIKE '["%',false),
      'imagesUnquotedBracketList',coalesce(ltrim(snapshot->>'images') LIKE '[%' AND ltrim(snapshot->>'images') NOT LIKE '["%',false)
    ) ELSE '{}'::jsonb END
  ), '[]'::jsonb,snapshot,created_at,
  'migration:0001_content_publication','migration:0001_content_publication',jsonb_build_object('valid',true,'mode','audited-legacy-bootstrap')
FROM hashed ON CONFLICT(item_id,payload_checksum) DO NOTHING;

UPDATE public.content_items i SET active_version_id=v.id
FROM public.content_versions v
WHERE v.item_id=i.id AND i.active_version_id IS NULL
AND CASE i.content_type
  WHEN 'hotel' THEN EXISTS(SELECT 1 FROM public.hotels x WHERE x.slug=i.slug AND coalesce(x.published,0)=1)
  WHEN 'brand' THEN EXISTS(SELECT 1 FROM public.brands x WHERE x.slug=i.slug AND coalesce(x.published,0)=1)
  WHEN 'destination' THEN EXISTS(SELECT 1 FROM public.destinations x WHERE x.slug=i.slug AND coalesce(x.published,0)=1)
  WHEN 'article' THEN EXISTS(SELECT 1 FROM public.articles x WHERE x.slug=i.slug AND coalesce(x.published,0)=1)
END;

INSERT INTO public.content_publication_events(item_id,event_type,previous_version_id,next_version_id,actor,run_id,occurred_at,verification_evidence,predecessor_state)
SELECT i.id,'bootstrap',NULL,i.active_version_id,'migration:0001_content_publication','migration:0001_content_publication',i.updated_at,
  jsonb_build_object('mode','audited-legacy-bootstrap','published',i.active_version_id IS NOT NULL),
  jsonb_build_object('itemExisted',true,'legacyExisted',true,'legacyRow',v.legacy_snapshot,'activeVersionId',i.active_version_id)
FROM public.content_items i JOIN public.content_versions v ON v.item_id=i.id
WHERE v.created_by='migration:0001_content_publication'
AND NOT EXISTS(SELECT 1 FROM public.content_publication_events e WHERE e.item_id=i.id AND e.event_type='bootstrap' AND e.run_id='migration:0001_content_publication');

CREATE OR REPLACE FUNCTION public.content_is_canonical_https_url(p_value text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE u text;
BEGIN
  IF p_value IS NULL OR length(p_value) NOT BETWEEN 1 AND 2048 OR p_value !~ '^https://[^/?#]+(?:[/?][^#]*)?$' OR position('#' IN p_value)>0 THEN RETURN false; END IF;
  u:=split_part(split_part(substr(p_value,9),'/',1),'?',1);
  RETURN u<>'' AND position('@' IN u)=0 AND lower(u)!~'^(localhost|[^:]+\.localhost)(:[0-9]+)?$'
    AND lower(u)!~'^(127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2[0-9]|3[01])\.)'
    AND lower(u)!~'^\[(::|::1|fc[0-9a-f:]*|fd[0-9a-f:]*|fe[89ab][0-9a-f:]*)\](:[0-9]+)?$';
END $$;

CREATE OR REPLACE FUNCTION public.content_is_timestamp(p_value text) RETURNS boolean
LANGUAGE plpgsql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
  RETURN p_value ~ '^[0-9]{4}-(0[1-9]|1[0-2])-([0-2][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]\.[0-9]{3}Z$'
    AND to_char(p_value::timestamptz AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')=p_value;
EXCEPTION WHEN others THEN RETURN false;
END $$;

CREATE OR REPLACE FUNCTION public.enforce_content_version_integrity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE item_slug text; canonical jsonb; hex text; expected uuid; expected_keys text[]; referenced text[]; manifest_urls text[]; super boolean;
BEGIN
  SELECT slug INTO STRICT item_slug FROM public.content_items WHERE id=NEW.item_id AND content_type=NEW.content_type;
  canonical:=jsonb_build_object('schemaVersion',NEW.schema_version,'contentType',NEW.content_type,'slug',item_slug,'payload',NEW.payload);
  hex:=encode(digest(convert_to(canonical::text,'UTF8'),'sha256'),'hex'); expected:=public.content_uuid_from_hex(hex);
  IF NEW.payload_checksum<>'sha256:'||hex OR NEW.id<>expected THEN RAISE EXCEPTION 'checksum or deterministic version ID mismatch' USING ERRCODE='23514'; END IF;
  IF NEW.validation_result->>'mode'='audited-legacy-bootstrap' THEN
    SELECT rolsuper INTO super FROM pg_catalog.pg_roles WHERE rolname=current_user;
    IF NOT coalesce(super,false) OR NEW.created_by<>'migration:0001_content_publication' OR NEW.run_id<>'migration:0001_content_publication' THEN RAISE EXCEPTION 'legacy bootstrap is migration-only' USING ERRCODE='42501'; END IF;
    RETURN NEW;
  END IF;
  expected_keys:=CASE NEW.content_type
    WHEN 'hotel' THEN ARRAY['name','brand','brandSlug','location','country','countrySlug','region','regionSlug','latitude','longitude','priceRange','priceFrom','priceTo','currency','style','bestFor','heroImage','images','website','bookingUrl','tagline','reviewIntro','reviewArrival','reviewRoom','reviewService','reviewFood','reviewDetails','reviewVerdict','verdictBestFor','verdictSkipIf','verdictStandout','ratingOverall','ratingRoom','ratingService','ratingFood','ratingValue','ratingLocation','featured','createdAt','updatedAt']
    WHEN 'brand' THEN ARRAY['name','tagline','heroImage','contentMd','hotelCount','foundedYear','parentCompany','bestProperty','website','createdAt','updatedAt']
    WHEN 'destination' THEN ARRAY['name','country','region','heroImage','introMd','bestTime','contentMd','createdAt','updatedAt']
    ELSE ARRAY['title','subtitle','category','heroImage','contentMd','hotelsMentioned','featured','createdAt','updatedAt'] END;
  IF jsonb_typeof(NEW.payload)<>'object' OR (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(NEW.payload) k) IS DISTINCT FROM (SELECT array_agg(k ORDER BY k) FROM unnest(expected_keys) k)
     OR (NEW.content_type='article' AND NEW.payload->>'category' NOT IN ('the-details','versus','new-openings'))
     OR NOT public.content_is_timestamp(NEW.payload->>'createdAt') OR NOT public.content_is_timestamp(NEW.payload->>'updatedAt')
     OR coalesce(NEW.payload->>'name',NEW.payload->>'title','')='' THEN RAISE EXCEPTION 'malformed or route-incompatible payload' USING ERRCODE='23514'; END IF;
  IF jsonb_typeof(NEW.source_evidence)<>'object'
     OR (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(NEW.source_evidence) k)<>ARRAY['claims','hardGates','revisionCount','sources']
     OR NEW.source_evidence->'hardGates'<>'{"truth":true,"userValue":true,"informationGain":true,"internalLinks":true,"editorialSameness":true}'::jsonb
     OR jsonb_typeof(NEW.source_evidence->'sources')<>'array' OR jsonb_array_length(NEW.source_evidence->'sources') NOT BETWEEN 1 AND 100
     OR jsonb_typeof(NEW.source_evidence->'claims')<>'array' OR jsonb_array_length(NEW.source_evidence->'claims') NOT BETWEEN 1 AND 200
     OR (NEW.source_evidence->>'revisionCount') !~ '^[0-2]$' THEN RAISE EXCEPTION 'incomplete source evidence' USING ERRCODE='23514'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.source_evidence->'sources') s WHERE
      (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(s) k)<>ARRAY['checkedAt','id','url'] OR NOT public.content_is_canonical_https_url(s->>'url') OR NOT public.content_is_timestamp(s->>'checkedAt') OR coalesce(s->>'id','')='')
     OR (SELECT count(*) FROM jsonb_array_elements(NEW.source_evidence->'sources'))<>(SELECT count(DISTINCT s->>'id') FROM jsonb_array_elements(NEW.source_evidence->'sources') s)
     OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.source_evidence->'claims') c WHERE
       (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(c) k)<>ARRAY['claim','sourceIds']
       OR jsonb_typeof(c->'sourceIds')<>'array' OR jsonb_array_length(c->'sourceIds')<1 OR coalesce(c->>'claim','')=''
       OR (SELECT count(*) FROM jsonb_array_elements_text(c->'sourceIds'))<>(SELECT count(DISTINCT sid) FROM jsonb_array_elements_text(c->'sourceIds') sid)
       OR EXISTS(SELECT 1 FROM jsonb_array_elements_text(c->'sourceIds') sid WHERE NOT EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.source_evidence->'sources') s WHERE s->>'id'=sid)))
  THEN RAISE EXCEPTION 'malformed claims or sources' USING ERRCODE='23514'; END IF;
  IF NEW.validation_result->>'valid'<>'true' OR NEW.validation_result->>'validator'<>'turndown-content-envelope-v1'
     OR NEW.validation_result->>'checksum' IS DISTINCT FROM NEW.payload_checksum
     OR NEW.validation_result#>>'{preflight,checksum}' IS DISTINCT FROM NEW.payload_checksum
     OR NEW.validation_result#>>'{preflight,renderer}'<>'the-turndown-marked-gfm-breaks-sanitized-v1' THEN RAISE EXCEPTION 'validation does not bind renderer and checksum' USING ERRCODE='23514'; END IF;
  IF jsonb_typeof(NEW.media_manifest)<>'array' OR jsonb_array_length(NEW.media_manifest)>100
     OR EXISTS(SELECT 1 FROM jsonb_array_elements(NEW.media_manifest) m WHERE
       (SELECT array_agg(k ORDER BY k) FROM jsonb_object_keys(m) k)<>ARRAY['byteLength','checksum','contentType','height','provenance','retrievedAt','url','width']
       OR NOT public.content_is_canonical_https_url(m->>'url') OR m->>'checksum' !~ '^sha256:[0-9a-f]{64}$'
       OR m->>'contentType' NOT IN ('image/png','image/jpeg','image/webp') OR (m->>'width')::integer NOT BETWEEN 1 AND 20000
       OR (m->>'height')::integer NOT BETWEEN 1 AND 20000 OR (m->>'byteLength')::integer NOT BETWEEN 1 AND 20000000
       OR NOT public.content_is_timestamp(m->>'retrievedAt')) THEN RAISE EXCEPTION 'malformed media manifest' USING ERRCODE='23514'; END IF;
  referenced:=ARRAY(SELECT x FROM (SELECT NEW.payload->>'heroImage' x UNION ALL SELECT jsonb_array_elements_text(CASE WHEN NEW.content_type='hotel' THEN NEW.payload->'images' ELSE '[]'::jsonb END)) q WHERE x IS NOT NULL);
  manifest_urls:=ARRAY(SELECT m->>'url' FROM jsonb_array_elements(NEW.media_manifest) m);
  IF referenced IS DISTINCT FROM manifest_urls AND (SELECT array_agg(x ORDER BY x) FROM unnest(referenced) x) IS DISTINCT FROM (SELECT array_agg(x ORDER BY x) FROM unnest(manifest_urls) x) THEN
    RAISE EXCEPTION 'media manifest does not exactly bind referenced images' USING ERRCODE='23514'; END IF;
  RETURN NEW;
EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN RAISE EXCEPTION 'malformed numeric media or payload field' USING ERRCODE='23514';
END $$;

DROP TRIGGER IF EXISTS content_versions_insert_integrity ON public.content_versions;
CREATE TRIGGER content_versions_insert_integrity BEFORE INSERT ON public.content_versions FOR EACH ROW EXECUTE FUNCTION public.enforce_content_version_integrity();

CREATE OR REPLACE FUNCTION public.reject_immutable_content_record() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public, pg_temp AS $$ BEGIN RAISE EXCEPTION '% is immutable',TG_TABLE_NAME USING ERRCODE='55000'; END $$;
DROP TRIGGER IF EXISTS content_versions_immutable ON public.content_versions;
CREATE TRIGGER content_versions_immutable BEFORE UPDATE OR DELETE ON public.content_versions FOR EACH ROW EXECUTE FUNCTION public.reject_immutable_content_record();
DROP TRIGGER IF EXISTS content_events_immutable ON public.content_publication_events;
CREATE TRIGGER content_events_immutable BEFORE UPDATE OR DELETE ON public.content_publication_events FOR EACH ROW EXECUTE FUNCTION public.reject_immutable_content_record();
DROP TRIGGER IF EXISTS content_keys_immutable ON public.content_validation_keys;
CREATE TRIGGER content_keys_immutable BEFORE UPDATE OR DELETE ON public.content_validation_keys FOR EACH ROW EXECUTE FUNCTION public.reject_immutable_content_record();

CREATE OR REPLACE FUNCTION public.enforce_content_item_identity() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
  IF NEW.id IS DISTINCT FROM OLD.id OR NEW.content_type IS DISTINCT FROM OLD.content_type OR NEW.slug IS DISTINCT FROM OLD.slug OR NEW.legacy_id IS DISTINCT FROM OLD.legacy_id OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'content item identity is immutable' USING ERRCODE='55000';
  END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS content_items_identity_immutable ON public.content_items;
CREATE TRIGGER content_items_identity_immutable BEFORE UPDATE ON public.content_items FOR EACH ROW EXECUTE FUNCTION public.enforce_content_item_identity();

DO $$ BEGIN CREATE ROLE turndown_content_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE ROLE turndown_content_publisher NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
ALTER ROLE turndown_content_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
ALTER ROLE turndown_content_publisher NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS;
DO $$
DECLARE edge record;
BEGIN
  FOR edge IN
    SELECT parent.rolname parent_name,member.rolname member_name
    FROM pg_catalog.pg_auth_members m
    JOIN pg_catalog.pg_roles parent ON parent.oid=m.roleid
    JOIN pg_catalog.pg_roles member ON member.oid=m.member
    WHERE parent.rolname IN ('turndown_content_runtime','turndown_content_publisher')
       OR member.rolname IN ('turndown_content_runtime','turndown_content_publisher')
  LOOP EXECUTE format('REVOKE %I FROM %I CASCADE',edge.parent_name,edge.member_name); END LOOP;
END $$;

CREATE OR REPLACE FUNCTION public.content_legacy_snapshot(p_type text,p_slug text) RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE r jsonb;
BEGIN
  CASE p_type
    WHEN 'hotel' THEN SELECT to_jsonb(x.*) INTO r FROM public.hotels x WHERE slug=p_slug;
    WHEN 'brand' THEN SELECT to_jsonb(x.*) INTO r FROM public.brands x WHERE slug=p_slug;
    WHEN 'destination' THEN SELECT to_jsonb(x.*) INTO r FROM public.destinations x WHERE slug=p_slug;
    WHEN 'article' THEN SELECT to_jsonb(x.*) INTO r FROM public.articles x WHERE slug=p_slug;
    ELSE RAISE EXCEPTION 'unsupported content type' USING ERRCODE='22023';
  END CASE;
  RETURN r;
END $$;

CREATE OR REPLACE FUNCTION public.content_snapshot_from_payload(p_type text,p_id text,p_slug text,p_payload jsonb,p_published integer) RETURNS jsonb
LANGUAGE plpgsql IMMUTABLE SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
  CASE p_type
    WHEN 'hotel' THEN RETURN jsonb_build_object('id',p_id,'slug',p_slug,'name',p_payload->'name','brand',p_payload->'brand','brand_slug',p_payload->'brandSlug','location',p_payload->'location','country',p_payload->'country','country_slug',p_payload->'countrySlug','region',p_payload->'region','region_slug',p_payload->'regionSlug','latitude',p_payload->'latitude','longitude',p_payload->'longitude','price_range',p_payload->'priceRange','price_from',p_payload->'priceFrom','price_to',p_payload->'priceTo','currency',p_payload->'currency','style',p_payload->'style','best_for',to_jsonb((p_payload->'bestFor')::text),'hero_image',p_payload->'heroImage','images',to_jsonb((p_payload->'images')::text),'website',p_payload->'website','booking_url',p_payload->'bookingUrl','tagline',p_payload->'tagline','review_intro',p_payload->'reviewIntro','review_arrival',p_payload->'reviewArrival','review_room',p_payload->'reviewRoom','review_service',p_payload->'reviewService','review_food',p_payload->'reviewFood','review_details',p_payload->'reviewDetails','review_verdict',p_payload->'reviewVerdict','verdict_best_for',p_payload->'verdictBestFor','verdict_skip_if',p_payload->'verdictSkipIf','verdict_standout',p_payload->'verdictStandout','rating_overall',p_payload->'ratingOverall','rating_room',p_payload->'ratingRoom','rating_service',p_payload->'ratingService','rating_food',p_payload->'ratingFood','rating_value',p_payload->'ratingValue','rating_location',p_payload->'ratingLocation','published',p_published,'featured',CASE WHEN (p_payload->>'featured')::boolean THEN 1 ELSE 0 END,'created_at',p_payload->'createdAt','updated_at',p_payload->'updatedAt');
    WHEN 'brand' THEN RETURN jsonb_build_object('id',p_id,'slug',p_slug,'name',p_payload->'name','tagline',p_payload->'tagline','hero_image',p_payload->'heroImage','content_md',p_payload->'contentMd','hotel_count',p_payload->'hotelCount','founded_year',p_payload->'foundedYear','parent_company',p_payload->'parentCompany','best_property',p_payload->'bestProperty','website',p_payload->'website','published',p_published,'created_at',p_payload->'createdAt','updated_at',p_payload->'updatedAt');
    WHEN 'destination' THEN RETURN jsonb_build_object('id',p_id,'slug',p_slug,'name',p_payload->'name','country',p_payload->'country','region',p_payload->'region','hero_image',p_payload->'heroImage','intro_md',p_payload->'introMd','best_time',p_payload->'bestTime','content_md',p_payload->'contentMd','published',p_published,'created_at',p_payload->'createdAt','updated_at',p_payload->'updatedAt');
    WHEN 'article' THEN RETURN jsonb_build_object('id',p_id,'slug',p_slug,'title',p_payload->'title','subtitle',p_payload->'subtitle','category',p_payload->'category','hero_image',p_payload->'heroImage','content_md',p_payload->'contentMd','hotels_mentioned',to_jsonb((p_payload->'hotelsMentioned')::text),'published',p_published,'featured',CASE WHEN (p_payload->>'featured')::boolean THEN 1 ELSE 0 END,'created_at',p_payload->'createdAt','updated_at',p_payload->'updatedAt');
    ELSE RAISE EXCEPTION 'unsupported content type' USING ERRCODE='22023';
  END CASE;
END $$;

CREATE OR REPLACE FUNCTION public.content_restore_legacy(p_type text,p_row jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
BEGIN
  CASE p_type
    WHEN 'hotel' THEN INSERT INTO public.hotels SELECT * FROM jsonb_populate_record(NULL::public.hotels,p_row) ON CONFLICT(slug) DO UPDATE SET (id,name,brand,brand_slug,location,country,country_slug,region,region_slug,latitude,longitude,price_range,price_from,price_to,currency,style,best_for,hero_image,images,website,booking_url,tagline,review_intro,review_arrival,review_room,review_service,review_food,review_details,review_verdict,verdict_best_for,verdict_skip_if,verdict_standout,rating_overall,rating_room,rating_service,rating_food,rating_value,rating_location,published,featured,created_at,updated_at)=(EXCLUDED.id,EXCLUDED.name,EXCLUDED.brand,EXCLUDED.brand_slug,EXCLUDED.location,EXCLUDED.country,EXCLUDED.country_slug,EXCLUDED.region,EXCLUDED.region_slug,EXCLUDED.latitude,EXCLUDED.longitude,EXCLUDED.price_range,EXCLUDED.price_from,EXCLUDED.price_to,EXCLUDED.currency,EXCLUDED.style,EXCLUDED.best_for,EXCLUDED.hero_image,EXCLUDED.images,EXCLUDED.website,EXCLUDED.booking_url,EXCLUDED.tagline,EXCLUDED.review_intro,EXCLUDED.review_arrival,EXCLUDED.review_room,EXCLUDED.review_service,EXCLUDED.review_food,EXCLUDED.review_details,EXCLUDED.review_verdict,EXCLUDED.verdict_best_for,EXCLUDED.verdict_skip_if,EXCLUDED.verdict_standout,EXCLUDED.rating_overall,EXCLUDED.rating_room,EXCLUDED.rating_service,EXCLUDED.rating_food,EXCLUDED.rating_value,EXCLUDED.rating_location,EXCLUDED.published,EXCLUDED.featured,EXCLUDED.created_at,EXCLUDED.updated_at);
    WHEN 'brand' THEN INSERT INTO public.brands SELECT * FROM jsonb_populate_record(NULL::public.brands,p_row) ON CONFLICT(slug) DO UPDATE SET (id,name,tagline,hero_image,content_md,hotel_count,founded_year,parent_company,best_property,website,published,created_at,updated_at)=(EXCLUDED.id,EXCLUDED.name,EXCLUDED.tagline,EXCLUDED.hero_image,EXCLUDED.content_md,EXCLUDED.hotel_count,EXCLUDED.founded_year,EXCLUDED.parent_company,EXCLUDED.best_property,EXCLUDED.website,EXCLUDED.published,EXCLUDED.created_at,EXCLUDED.updated_at);
    WHEN 'destination' THEN INSERT INTO public.destinations SELECT * FROM jsonb_populate_record(NULL::public.destinations,p_row) ON CONFLICT(slug) DO UPDATE SET (id,name,country,region,hero_image,intro_md,best_time,content_md,published,created_at,updated_at)=(EXCLUDED.id,EXCLUDED.name,EXCLUDED.country,EXCLUDED.region,EXCLUDED.hero_image,EXCLUDED.intro_md,EXCLUDED.best_time,EXCLUDED.content_md,EXCLUDED.published,EXCLUDED.created_at,EXCLUDED.updated_at);
    WHEN 'article' THEN INSERT INTO public.articles SELECT * FROM jsonb_populate_record(NULL::public.articles,p_row) ON CONFLICT(slug) DO UPDATE SET (id,title,subtitle,category,hero_image,content_md,hotels_mentioned,published,featured,created_at,updated_at)=(EXCLUDED.id,EXCLUDED.title,EXCLUDED.subtitle,EXCLUDED.category,EXCLUDED.hero_image,EXCLUDED.content_md,EXCLUDED.hotels_mentioned,EXCLUDED.published,EXCLUDED.featured,EXCLUDED.created_at,EXCLUDED.updated_at);
    ELSE RAISE EXCEPTION 'unsupported content type' USING ERRCODE='22023';
  END CASE;
END $$;

CREATE OR REPLACE FUNCTION public.content_validation_challenge(p_type text,p_slug text,p_checksum text,p_payload jsonb,p_evidence jsonb,p_media jsonb,p_validation jsonb) RETURNS text
LANGUAGE sql IMMUTABLE SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
 SELECT encode(digest(convert_to(concat_ws(E'\n',p_type,p_slug,p_checksum,p_payload::text,p_evidence::text,p_media::text,(p_validation-'validatorProof')::text),'UTF8'),'sha256'),'hex')
$$;

CREATE OR REPLACE FUNCTION public.content_has_pending(p_item uuid) RETURNS boolean
LANGUAGE sql STABLE SET search_path = pg_catalog, public, pg_temp AS $$
 SELECT EXISTS(SELECT 1 FROM public.content_publication_events e WHERE e.item_id=p_item AND e.activation_event_id IS NULL AND e.event_type IN ('published','reactivated','rolled_back')
   AND NOT EXISTS(SELECT 1 FROM public.content_publication_events o WHERE o.activation_event_id=e.id AND o.event_type IN ('verified','verification_failed'))
   AND e.id=(SELECT z.id FROM public.content_publication_events z WHERE z.item_id=p_item AND z.activation_event_id IS NULL AND z.event_type IN ('published','reactivated','rolled_back') ORDER BY z.event_order DESC LIMIT 1))
$$;

CREATE OR REPLACE FUNCTION public.publish_content_version(p_type text,p_slug text,p_version_id uuid,p_checksum text,p_payload jsonb,p_evidence jsonb,p_media jsonb,p_actor text,p_run_id text,p_validation jsonb)
RETURNS TABLE(changed boolean,item_id uuid,content_type text,previous_version_id uuid,previous_published boolean,version_id uuid,checksum text,activation_event_id uuid)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE i public.content_items%ROWTYPE; v public.content_versions%ROWTYPE; proof text; event_id uuid:=gen_random_uuid(); predecessor jsonb; legacy jsonb; new_snapshot jsonb; existed boolean; changed_value boolean; legacy_id text;
BEGIN
  IF p_type NOT IN ('hotel','brand','destination','article') OR p_slug!~'^[a-z0-9]+(-[a-z0-9]+)*$' OR p_actor='' OR p_actor<>btrim(p_actor) OR length(p_actor)>200 OR p_run_id='' OR p_run_id<>btrim(p_run_id) OR length(p_run_id)>200 THEN RAISE EXCEPTION 'invalid publication identity or actor' USING ERRCODE='22023'; END IF;
  IF p_validation->>'checksum' IS DISTINCT FROM p_checksum OR p_validation#>>'{preflight,checksum}' IS DISTINCT FROM p_checksum OR p_validation#>>'{preflight,renderer}'<>'the-turndown-marked-gfm-breaks-sanitized-v1' THEN RAISE EXCEPTION 'validation binding mismatch' USING ERRCODE='22023'; END IF;
  SELECT encode(hmac(decode(public.content_validation_challenge(p_type,p_slug,p_checksum,p_payload,p_evidence,p_media,p_validation),'hex'),k.secret,'sha256'),'hex') INTO STRICT proof FROM public.content_validation_keys k WHERE singleton;
  IF p_validation->>'validatorProof' IS DISTINCT FROM proof THEN RAISE EXCEPTION 'invalid validator proof' USING ERRCODE='42501'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('turndown:content:'||p_type||':'||p_slug,0));
  SELECT x.* INTO i FROM public.content_items x WHERE x.content_type=p_type AND x.slug=p_slug FOR UPDATE; existed:=FOUND;
  IF NOT existed THEN
    legacy_id:=public.content_uuid_from_hex(encode(digest(convert_to(p_type||':'||p_slug,'UTF8'),'sha256'),'hex'))::text;
    INSERT INTO public.content_items(id,content_type,slug,legacy_id,created_at,updated_at) VALUES(legacy_id::uuid,p_type,p_slug,legacy_id,(p_payload->>'createdAt')::timestamptz,(p_payload->>'updatedAt')::timestamptz) RETURNING * INTO i;
    new_snapshot:=public.content_snapshot_from_payload(p_type,legacy_id,p_slug,p_payload,0); PERFORM public.content_restore_legacy(p_type,new_snapshot);
  END IF;
  IF public.content_has_pending(i.id) THEN RAISE EXCEPTION 'pending activation must be recovered before publication' USING ERRCODE='40001'; END IF;
  legacy:=public.content_legacy_snapshot(p_type,p_slug);
  predecessor:=jsonb_build_object('itemExisted',existed,'legacyExisted',legacy IS NOT NULL,'legacyRow',legacy,'activeVersionId',i.active_version_id,'published',coalesce((legacy->>'published')::integer,0)=1,'createdAsDraft',NOT existed);
  SELECT x.* INTO v FROM public.content_versions x WHERE x.item_id=i.id AND x.payload_checksum=p_checksum;
  new_snapshot:=public.content_snapshot_from_payload(p_type,i.legacy_id,p_slug,p_payload,1);
  IF FOUND THEN
    IF v.id<>p_version_id OR v.payload IS DISTINCT FROM p_payload OR v.source_evidence IS DISTINCT FROM p_evidence OR v.media_manifest IS DISTINCT FROM p_media OR v.validation_result IS DISTINCT FROM p_validation OR v.legacy_snapshot IS DISTINCT FROM new_snapshot THEN RAISE EXCEPTION 'altered immutable version reuse denied' USING ERRCODE='40001'; END IF;
  ELSE
    IF EXISTS(SELECT 1 FROM public.content_versions x WHERE x.id=p_version_id) THEN RAISE EXCEPTION 'deterministic version ID collision' USING ERRCODE='23505'; END IF;
    INSERT INTO public.content_versions(id,item_id,content_type,schema_version,payload,payload_checksum,source_evidence,media_manifest,legacy_snapshot,created_at,created_by,run_id,validation_result)
      VALUES(p_version_id,i.id,p_type,1,p_payload,p_checksum,p_evidence,p_media,new_snapshot,(p_payload->>'createdAt')::timestamptz,p_actor,p_run_id,p_validation) RETURNING * INTO v;
  END IF;
  changed_value:=i.active_version_id IS DISTINCT FROM v.id OR coalesce((legacy->>'published')::integer,0)<>1;
  UPDATE public.content_items SET active_version_id=v.id,updated_at=(p_payload->>'updatedAt')::timestamptz WHERE id=i.id;
  PERFORM public.content_restore_legacy(p_type,v.legacy_snapshot);
  INSERT INTO public.content_publication_events(id,item_id,event_type,previous_version_id,next_version_id,actor,run_id,predecessor_state)
    VALUES(event_id,i.id,CASE WHEN i.active_version_id IS NULL THEN 'published' ELSE 'reactivated' END,i.active_version_id,v.id,p_actor,p_run_id,predecessor);
  RETURN QUERY SELECT changed_value,i.id,p_type,i.active_version_id,coalesce((predecessor->>'published')::boolean,false),v.id,v.payload_checksum,event_id;
END $$;

CREATE OR REPLACE FUNCTION public.activate_content_version(p_type text,p_slug text,p_version_id uuid,p_kind text,p_actor text,p_run_id text)
RETURNS TABLE(changed boolean,item_id uuid,content_type text,previous_version_id uuid,previous_published boolean,version_id uuid,checksum text,activation_event_id uuid)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE i public.content_items%ROWTYPE; v public.content_versions%ROWTYPE; event_id uuid:=gen_random_uuid(); legacy jsonb; changed_value boolean;
BEGIN
  IF p_kind NOT IN ('reactivate','rollback') OR p_actor='' OR p_actor<>btrim(p_actor) OR p_run_id='' OR p_run_id<>btrim(p_run_id) THEN RAISE EXCEPTION 'invalid activation request' USING ERRCODE='22023'; END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('turndown:content:'||p_type||':'||p_slug,0));
  SELECT x.* INTO STRICT i FROM public.content_items x WHERE x.content_type=p_type AND x.slug=p_slug FOR UPDATE;
  IF public.content_has_pending(i.id) THEN RAISE EXCEPTION 'pending activation must be recovered before historical activation' USING ERRCODE='40001'; END IF;
  SELECT x.* INTO STRICT v FROM public.content_versions x WHERE x.id=p_version_id AND x.item_id=i.id AND x.content_type=p_type;
  legacy:=public.content_legacy_snapshot(p_type,p_slug); changed_value:=i.active_version_id IS DISTINCT FROM v.id OR coalesce((legacy->>'published')::integer,0)<>1;
  UPDATE public.content_items SET active_version_id=v.id,updated_at=(v.payload->>'updatedAt')::timestamptz WHERE id=i.id; PERFORM public.content_restore_legacy(p_type,v.legacy_snapshot);
  INSERT INTO public.content_publication_events(id,item_id,event_type,previous_version_id,next_version_id,actor,run_id,predecessor_state)
    VALUES(event_id,i.id,CASE WHEN p_kind='rollback' THEN 'rolled_back' ELSE 'reactivated' END,i.active_version_id,v.id,p_actor,p_run_id,jsonb_build_object('itemExisted',true,'legacyExisted',legacy IS NOT NULL,'legacyRow',legacy,'activeVersionId',i.active_version_id,'published',coalesce((legacy->>'published')::integer,0)=1));
  RETURN QUERY SELECT changed_value,i.id,p_type,i.active_version_id,coalesce((legacy->>'published')::integer,0)=1,v.id,v.payload_checksum,event_id;
END $$;

CREATE OR REPLACE FUNCTION public.read_active_content_payload(p_type text,p_slug text)
RETURNS TABLE(item_id uuid,content_type text,slug text,published boolean,version_id uuid,checksum text,payload jsonb,media jsonb,created_by text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
 SELECT i.id,i.content_type,i.slug,i.active_version_id IS NOT NULL,v.id,v.payload_checksum,v.payload,v.media_manifest,v.created_by
 FROM public.content_items i LEFT JOIN public.content_versions v ON v.id=i.active_version_id AND v.item_id=i.id AND v.content_type=i.content_type
 WHERE i.content_type=p_type AND i.slug=p_slug
$$;

CREATE OR REPLACE FUNCTION public.read_pending_content_activation(p_type text,p_slug text)
RETURNS TABLE(changed boolean,item_id uuid,content_type text,previous_version_id uuid,previous_published boolean,version_id uuid,checksum text,activation_event_id uuid,payload jsonb,media jsonb,created_by text)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
 SELECT true,e.item_id,i.content_type,e.previous_version_id,coalesce((e.predecessor_state->>'published')::boolean,false),e.next_version_id,v.payload_checksum,e.id,v.payload,v.media_manifest,v.created_by
 FROM public.content_publication_events e JOIN public.content_items i ON i.id=e.item_id AND i.content_type=p_type AND i.slug=p_slug
 JOIN public.content_versions v ON v.id=e.next_version_id AND v.item_id=e.item_id
 WHERE e.activation_event_id IS NULL AND e.event_type IN ('published','reactivated','rolled_back')
 AND NOT EXISTS(SELECT 1 FROM public.content_publication_events o WHERE o.activation_event_id=e.id AND o.event_type IN ('verified','verification_failed'))
 AND e.id=(SELECT z.id FROM public.content_publication_events z WHERE z.item_id=e.item_id AND z.activation_event_id IS NULL AND z.event_type IN ('published','reactivated','rolled_back') ORDER BY z.event_order DESC LIMIT 1) LIMIT 1
$$;

CREATE OR REPLACE FUNCTION public.record_content_verification(p_type text,p_slug text,p_activation uuid,p_version uuid,p_checksum text,p_evidence jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE i public.content_items%ROWTYPE; a public.content_publication_events%ROWTYPE; latest uuid; checksum_value text;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('turndown:content:'||p_type||':'||p_slug,0));
  SELECT x.* INTO STRICT i FROM public.content_items x WHERE x.content_type=p_type AND x.slug=p_slug FOR UPDATE;
  SELECT e.* INTO STRICT a FROM public.content_publication_events e WHERE e.id=p_activation AND e.item_id=i.id AND e.activation_event_id IS NULL AND e.event_type IN ('published','reactivated','rolled_back');
  SELECT e.id INTO latest FROM public.content_publication_events e WHERE e.item_id=i.id AND e.activation_event_id IS NULL AND e.event_type IN ('published','reactivated','rolled_back') ORDER BY e.event_order DESC LIMIT 1;
  SELECT v.payload_checksum INTO STRICT checksum_value FROM public.content_versions v WHERE v.id=p_version AND v.item_id=i.id;
  IF latest IS DISTINCT FROM p_activation OR a.next_version_id IS DISTINCT FROM p_version OR i.active_version_id IS DISTINCT FROM p_version OR checksum_value IS DISTINCT FROM p_checksum THEN RAISE EXCEPTION 'stale or mismatched verification settlement denied' USING ERRCODE='40001'; END IF;
  INSERT INTO public.content_publication_events(item_id,event_type,previous_version_id,next_version_id,actor,run_id,verification_evidence,activation_event_id)
    VALUES(i.id,'verified',p_version,p_version,'live-verifier','verify:'||p_activation,p_evidence||jsonb_build_object('activationEventId',p_activation,'versionId',p_version,'checksum',p_checksum),p_activation);
END $$;

CREATE OR REPLACE FUNCTION public.rollback_failed_content_verification(p_type text,p_slug text,p_activation uuid,p_error text) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE i public.content_items%ROWTYPE; a public.content_publication_events%ROWTYPE; latest uuid; state jsonb; failed uuid; restored uuid;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('turndown:content:'||p_type||':'||p_slug,0));
  SELECT x.* INTO STRICT i FROM public.content_items x WHERE x.content_type=p_type AND x.slug=p_slug FOR UPDATE;
  SELECT e.* INTO STRICT a FROM public.content_publication_events e WHERE e.id=p_activation AND e.item_id=i.id AND e.activation_event_id IS NULL AND e.event_type IN ('published','reactivated','rolled_back');
  SELECT e.id INTO latest FROM public.content_publication_events e WHERE e.item_id=i.id AND e.activation_event_id IS NULL AND e.event_type IN ('published','reactivated','rolled_back') ORDER BY e.event_order DESC LIMIT 1;
  failed:=a.next_version_id; state:=a.predecessor_state;
  IF EXISTS(SELECT 1 FROM public.content_publication_events e WHERE e.activation_event_id=p_activation AND e.event_type='rolled_back')
     AND NOT EXISTS(SELECT 1 FROM public.content_publication_events e WHERE e.activation_event_id=p_activation AND e.event_type IN ('verified','verification_failed')) THEN RETURN; END IF;
  IF latest IS DISTINCT FROM p_activation OR i.active_version_id IS DISTINCT FROM failed OR EXISTS(SELECT 1 FROM public.content_publication_events e WHERE e.activation_event_id=p_activation AND e.event_type IN ('verified','verification_failed')) THEN RAISE EXCEPTION 'stale or already-settled activation rollback denied' USING ERRCODE='40001'; END IF;
  restored:=CASE WHEN state->'activeVersionId'='null'::jsonb THEN NULL ELSE (state->>'activeVersionId')::uuid END;
  UPDATE public.content_items SET active_version_id=restored,updated_at=CASE WHEN state->'legacyRow' IS NULL OR state->'legacyRow'='null'::jsonb THEN updated_at ELSE (state#>>'{legacyRow,updated_at}')::timestamptz END WHERE id=i.id;
  IF coalesce((state->>'legacyExisted')::boolean,false) THEN PERFORM public.content_restore_legacy(p_type,state->'legacyRow'); END IF;
  INSERT INTO public.content_publication_events(item_id,event_type,previous_version_id,next_version_id,actor,run_id,verification_evidence,activation_event_id)
    VALUES(i.id,'rolled_back',failed,restored,'live-verifier','verification-rollback:'||p_activation,jsonb_build_object('reason','live-verification-failed','restoredPublished',coalesce((state->>'published')::boolean,false)),p_activation);
END $$;

CREATE OR REPLACE FUNCTION public.record_content_restoration_verification(p_type text,p_slug text,p_activation uuid,p_evidence jsonb) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public, pg_temp AS $$
DECLARE i public.content_items%ROWTYPE; a public.content_publication_events%ROWTYPE; restored uuid;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended('turndown:content:'||p_type||':'||p_slug,0));
  SELECT x.* INTO STRICT i FROM public.content_items x WHERE x.content_type=p_type AND x.slug=p_slug FOR UPDATE;
  SELECT e.* INTO STRICT a FROM public.content_publication_events e WHERE e.id=p_activation AND e.item_id=i.id AND e.activation_event_id IS NULL AND e.event_type IN ('published','reactivated','rolled_back');
  restored:=CASE WHEN a.predecessor_state->'activeVersionId'='null'::jsonb THEN NULL ELSE (a.predecessor_state->>'activeVersionId')::uuid END;
  IF i.active_version_id IS DISTINCT FROM restored
     OR NOT EXISTS(SELECT 1 FROM public.content_publication_events e WHERE e.activation_event_id=p_activation AND e.event_type='rolled_back')
     OR EXISTS(SELECT 1 FROM public.content_publication_events e WHERE e.activation_event_id=p_activation AND e.event_type IN ('verified','verification_failed')) THEN
    RAISE EXCEPTION 'restoration verification is stale or mismatched' USING ERRCODE='40001';
  END IF;
  INSERT INTO public.content_publication_events(item_id,event_type,previous_version_id,next_version_id,actor,run_id,verification_evidence,activation_event_id)
    VALUES(i.id,'verification_failed',a.next_version_id,restored,'live-verifier','restoration:'||p_activation,p_evidence||jsonb_build_object('activationEventId',p_activation,'failedVersionId',a.next_version_id,'restoredVersionId',restored),p_activation);
END $$;

-- Harden ownership and expose only runtime reads / publisher definer calls.
REVOKE ALL ON public.content_items,public.content_versions,public.content_publication_events,public.content_validation_keys FROM PUBLIC,turndown_content_publisher;
REVOKE ALL ON FUNCTION public.content_legacy_snapshot(text,text),public.content_snapshot_from_payload(text,text,text,jsonb,integer),
  public.content_restore_legacy(text,jsonb),public.content_has_pending(uuid) FROM PUBLIC,turndown_content_runtime,turndown_content_publisher;
GRANT USAGE ON SCHEMA public TO turndown_content_runtime,turndown_content_publisher;
GRANT SELECT ON public.content_items,public.content_versions TO turndown_content_runtime;

DO $$
DECLARE oid_value oid; role_name text;
BEGIN
  FOREACH oid_value IN ARRAY ARRAY[
    'public.content_validation_challenge(text,text,text,jsonb,jsonb,jsonb,jsonb)'::regprocedure::oid,
    'public.publish_content_version(text,text,uuid,text,jsonb,jsonb,jsonb,text,text,jsonb)'::regprocedure::oid,
    'public.activate_content_version(text,text,uuid,text,text,text)'::regprocedure::oid,
    'public.read_active_content_payload(text,text)'::regprocedure::oid,
    'public.read_pending_content_activation(text,text)'::regprocedure::oid,
    'public.record_content_verification(text,text,uuid,uuid,text,jsonb)'::regprocedure::oid,
    'public.rollback_failed_content_verification(text,text,uuid,text)'::regprocedure::oid,
    'public.record_content_restoration_verification(text,text,uuid,jsonb)'::regprocedure::oid
  ] LOOP
    EXECUTE format('ALTER FUNCTION %s OWNER TO %I',oid_value::regprocedure,current_user);
    EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',oid_value::regprocedure);
    FOR role_name IN SELECT r.rolname FROM pg_catalog.pg_proc p CROSS JOIN LATERAL pg_catalog.aclexplode(coalesce(p.proacl,pg_catalog.acldefault('f',p.proowner))) a JOIN pg_catalog.pg_roles r ON r.oid=a.grantee WHERE p.oid=oid_value AND a.privilege_type='EXECUTE' AND r.rolname NOT IN (current_user,'turndown_content_publisher')
    LOOP EXECUTE format('REVOKE ALL ON FUNCTION %s FROM %I',oid_value::regprocedure,role_name); END LOOP;
    EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO turndown_content_publisher',oid_value::regprocedure);
  END LOOP;
END $$;

COMMIT;
