CREATE TABLE public.hotels (
 id text PRIMARY KEY,slug text UNIQUE NOT NULL,name text NOT NULL,brand text,brand_slug text,location text,country text,country_slug text,region text,region_slug text,
 latitude double precision,longitude double precision,price_range text,price_from integer,price_to integer,currency text DEFAULT 'USD',style text,best_for text,hero_image text,images text,
 website text,booking_url text,tagline text,review_intro text,review_arrival text,review_room text,review_service text,review_food text,review_details text,review_verdict text,
 verdict_best_for text,verdict_skip_if text,verdict_standout text,rating_overall double precision,rating_room double precision,rating_service double precision,rating_food double precision,
 rating_value double precision,rating_location double precision,published integer DEFAULT 0,featured integer DEFAULT 0,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.brands (id text PRIMARY KEY,slug text UNIQUE NOT NULL,name text NOT NULL,tagline text,hero_image text,content_md text,hotel_count integer DEFAULT 0,founded_year integer,parent_company text,best_property text,website text,published integer DEFAULT 0,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.destinations (id text PRIMARY KEY,slug text UNIQUE NOT NULL,name text NOT NULL,country text,region text,hero_image text,intro_md text,best_time text,content_md text,published integer DEFAULT 0,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.articles (id text PRIMARY KEY,slug text UNIQUE NOT NULL,title text NOT NULL,subtitle text,category text NOT NULL,hero_image text,content_md text,hotels_mentioned text,published integer DEFAULT 0,featured integer DEFAULT 0,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.newsletter_subscribers (id serial PRIMARY KEY,email text UNIQUE NOT NULL,confirmed integer DEFAULT 0,resend_contact_id text,resend_synced_at timestamptz,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now());
CREATE TABLE public.newsletter_sends (id serial PRIMARY KEY,issue_key text NOT NULL,article_slug text NOT NULL,recipient_count integer NOT NULL DEFAULT 0,provider_message_ids text,sent_at timestamptz DEFAULT now(),UNIQUE(issue_key,article_slug));
